In [3]:
import numpy as np 

In [89]:
# 1)Write a Python program to add, subtract, multiply, divide arguments element-wise

array_1 = np.arange(1,26).reshape(5,5)
print(array_1)
array_2 = np.arange(26,51).reshape(5,5)
print("\n",array_2)
array_add = array_1+array_2
print("\nAddition\n",array_add)
array_sub = array_1-array_2
print("\nSubstraction\n",array_sub)
array_mul = array_1*array_2
print("\nMultiplication\n",array_mul)
array_div = array_1/array_2
print("\nDivision\n",array_div)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 [[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]

Addition
 [[27 29 31 33 35]
 [37 39 41 43 45]
 [47 49 51 53 55]
 [57 59 61 63 65]
 [67 69 71 73 75]]

Substraction
 [[-25 -25 -25 -25 -25]
 [-25 -25 -25 -25 -25]
 [-25 -25 -25 -25 -25]
 [-25 -25 -25 -25 -25]
 [-25 -25 -25 -25 -25]]

Multiplication
 [[  26   54   84  116  150]
 [ 186  224  264  306  350]
 [ 396  444  494  546  600]
 [ 656  714  774  836  900]
 [ 966 1034 1104 1176 1250]]

Division
 [[0.03846154 0.07407407 0.10714286 0.13793103 0.16666667]
 [0.19354839 0.21875    0.24242424 0.26470588 0.28571429]
 [0.30555556 0.32432432 0.34210526 0.35897436 0.375     ]
 [0.3902439  0.4047619  0.41860465 0.43181818 0.44444444]
 [0.45652174 0.46808511 0.47916667 0.48979592 0.5       ]]


In [103]:
# 2)Write a Python program to compute logarithm of the sum of exponentiations of the inputs, sum of exponentiations of the inputs in base-2
arr = np.arange(1,11)
print(arr)
arr = np.exp(arr)
total = arr.sum()
print("\nLog of sum of exponents\n",np.log(total))
print("\nLog to base 2 of sum of exponents\n",np.log2(total))

[ 1  2  3  4  5  6  7  8  9 10]

Log of sum of exponents
 10.45862974442671

Log to base 2 of sum of exponents
 15.088613266778223


In [104]:
# 3)Write a Python program to get true division of the element-wise array inputs
arr = np.arange(10).reshape(2,5)
print(arr)
print("\nTrue Division of the array element")
print(np.true_divide(arr, 3))

[[0 1 2 3 4]
 [5 6 7 8 9]]

True Division of the array element
[[0.         0.33333333 0.66666667 1.         1.33333333]
 [1.66666667 2.         2.33333333 2.66666667 3.        ]]


In [105]:
# 4)Write a Python program to get the largest integer smaller or equal to the division of the inputs.
arr = np.linspace(1,10,15)
print(arr)
print("\nFloor values")
print(np.floor(arr))

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]

Floor values
[ 1.  1.  2.  2.  3.  4.  4.  5.  6.  6.  7.  8.  8.  9. 10.]


In [45]:
# 5)Write a Python program to get the powers of an array values element-wise.
array_1 = np.arange(6,11)
print(array_1)
array_2 = np.arange(1,6)
print("\n",array_2)
print("\nPower of array_elements\n",array_1**array_2)

[ 6  7  8  9 10]

 [1 2 3 4 5]

Power of array_elements
 [     6     49    512   6561 100000]


In [48]:
# 6)Write a Python program to get the element-wise remainder of an array of division.
array_1 = np.arange(1,26).reshape(5,5)
print(array_1)
array_2 = np.arange(26,51).reshape(5,5)
print("\n",array_2)
print("\nReminder of elementwise division\n",array_2%array_1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 [[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]

Reminder of elementwise division
 [[ 0  1  1  1  0]
 [ 1  4  1  7  5]
 [ 3  1 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


In [53]:
# 7)Write a Python program to calculate the absolute value element-wise
array_1 = np.array([-1,2,-3,4,-5,6,7,-8,-9,10])
print(array_1)
print("\nElementwise absolute value")
print(np.absolute(array_1))

[-1  2 -3  4 -5  6  7 -8 -9 10]

Elementwise absolute value
[ 1  2  3  4  5  6  7  8  9 10]


In [84]:
# 8)Write a Python program to round array elements to the given number of decimals.
arr = np.linspace(1,5,25).reshape(5,5)
print(arr)
print("\nRounding Elements")
print(np.round(arr, decimals=2))

[[1.         1.16666667 1.33333333 1.5        1.66666667]
 [1.83333333 2.         2.16666667 2.33333333 2.5       ]
 [2.66666667 2.83333333 3.         3.16666667 3.33333333]
 [3.5        3.66666667 3.83333333 4.         4.16666667]
 [4.33333333 4.5        4.66666667 4.83333333 5.        ]]

Rounding Elements
[[1.   1.17 1.33 1.5  1.67]
 [1.83 2.   2.17 2.33 2.5 ]
 [2.67 2.83 3.   3.17 3.33]
 [3.5  3.67 3.83 4.   4.17]
 [4.33 4.5  4.67 4.83 5.  ]]


In [85]:
# 9)Write a Python program to round elements of the array to the nearest int
arr = np.linspace(1,10,15)
print(arr)
print("\nRounding Elements")
print(np.rint(arr))

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]

Rounding Elements
[ 1.  2.  2.  3.  4.  4.  5.  6.  6.  7.  7.  8.  9.  9. 10.]


In [88]:
# 10)Write a Python program to get the floor, ceiling and truncated values of the elements of an numpy
arr = np.linspace(1,10,15)
print(arr)
print("\nFloor values")
print(np.floor(arr))
print("\nCeil values")
print(np.ceil(arr))
print("Truncated values")
print(np.trunc(arr))

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]

Floor values
[ 1.  1.  2.  2.  3.  4.  4.  5.  6.  6.  7.  8.  8.  9. 10.]

Ceil values
[ 1.  2.  3.  3.  4.  5.  5.  6.  7.  7.  8.  9.  9. 10. 10.]
Truncated values
[ 1.  1.  2.  2.  3.  4.  4.  5.  6.  6.  7.  8.  8.  9. 10.]
