In [1]:
import numpy as np

In [77]:
# 1)Write a Python program to take values from a source array and put them at specified indices of another array.
array = np.arange(1,26).reshape(5,5)
print(array)
index_array = np.array([])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [3]:
# 2)Write a Python program to sum and compute the product of a numpy array elements
array = np.arange(1,7).reshape(2,3)
print(array)
print("\nSum of elements:\n",array.sum())
print("\nProduct of elements:\n",array.prod())

[[1 2 3]
 [4 5 6]]

Sum of elements:
 21

Product of elements:
 720


In [10]:
# 3)Write a Python program to convert the raw data in an array to a binary string and then create an array.
array_1 = np.array([10, 20, 30])
print(np.array2string(array_1))

[10 20 30]


In [64]:
# 4)Write a Python program to print all the values of an array
array = np.arange(1,26).reshape(5,5)
print(array)
for i in array.flat:
    print(i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25


In [27]:
# 5)Write a Python program to divide each row by a vector element
array = np.arange(1,26).reshape(5,5)
print(array)
array[:] *= 2
print("\nNew array\n",array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

New array
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]


In [30]:
# 6)Write a Python program to check whether the numpy array is empty or not.
array = np.array([])
if array.size == 0:
    print("Array is empty")
else:
    print("Array is not empty")

Array is empty


In [31]:
# 7)Write a Python program to count the frequency of unique values in numpy array.
array = np.arange(1,26).reshape(5,5)
array[0:-1,0:-1] = 1
print(array)
count = 0
for i in array.flat:
    if i == 1:
        count += 1
print("\nFrequency of element:\n",count)

[[ 1  1  1  1  5]
 [ 1  1  1  1 10]
 [ 1  1  1  1 15]
 [ 1  1  1  1 20]
 [21 22 23 24 25]]

Frequency of element:
 16


In [36]:
# 8)Write a Python program to get the magnitude of a vector in numpy
array = np.arange(1,26).reshape(5,5)
print(array.size)

25


In [106]:
# 9)Write a Python program to remove all rows in a numpy array that contain non-numeric values.
array = np.array([[1,np.nan,3,4,np.nan],[6,7,8,9,10],[11,12,13,np.nan,15],[16,17,np.nan,19,20],[21,22,23,24,25]])
print(array)
print("\nRemoving rows with NaN values\n",array[~np.isnan(array).any(axis=1)])
# print("\nRemoving column with NaN values\n",array[:,~np.isnan(array).any(axis=0)])
# print(np.isnan(np.nan))

[[ 1. nan  3.  4. nan]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. nan 15.]
 [16. 17. nan 19. 20.]
 [21. 22. 23. 24. 25.]]

Removing rows with NaN values
 [[ 6.  7.  8.  9. 10.]
 [21. 22. 23. 24. 25.]]
