In [3]:
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd

In [16]:
array_1 = np.arange(1,16).reshape(3,5)
array_1 = array_1.T
print(array_1)

array_2 = np.concatenate([array_1[1],array_1[3]])
print(array_2)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[ 2  7 12  4  9 14]


In [2]:
random_array = np.random.rand(10,3)
print(random_array)

[[0.97696586 0.20685782 0.48511647]
 [0.68547221 0.57498177 0.81129003]
 [0.34393809 0.72870928 0.80171677]
 [0.7104068  0.35724814 0.80825532]
 [0.63072753 0.44001155 0.02159193]
 [0.40350826 0.56635032 0.21957389]
 [0.54768484 0.8232191  0.61874818]
 [0.37006314 0.56486102 0.9777431 ]
 [0.03796599 0.0464768  0.57729852]
 [0.2665811  0.15357958 0.27354458]]


In [9]:
a = np.ones((6,6))
b = np.zeros((4,4))
c = np.arange(1,5).reshape(2,2)
b[1:3,1:3] = c
a[1:5,1:5] = b
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 1. 2. 0. 1.]
 [1. 0. 3. 4. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [13]:
identity_matrix = np.identity(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [17]:
array = np.arange(12).reshape(3,2,2)
print(array)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [23]:
array = np.ones((10,10))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [6]:
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [5]:
checkboard = np.tile([[1,0],[0,1]],(4,4))
print(checkboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [20]:
# 3. Write a NumPy program to test whether none of the elements of a given array is zero.
array = np.arange(25).reshape((5,5))
print(array)
print(np.all(array)) # return false if one element is zero

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
False


In [21]:
# 4. Write a NumPy program to test whether any of the elements of a given array is non-zero.
array = np.zeros((5,5))
print(array)
print(np.any(array)) # return true if one element is non zero

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
False


In [26]:
# 5. Write a NumPy program to test a given array element-wise for finiteness
array = np.zeros((5,5))
print(array)
print(np.isfinite(array))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [31]:
# 14. Write a NumPy program to create an array of the integers from 30 to70.
array = np.arange(30,71)
print(array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [33]:
# 15. Write a NumPy program to create an array of the integers from 30 to70.
array = np.arange(30,71,2)
print(array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [36]:
# 16. Write a NumPy program to create a 3x3 identity matrix
array = np.identity(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [59]:
# 17. Write a NumPy program to generate a random number between 0 and 1.
array = np.random.random(1)
print(array)

[0.50622899]


In [64]:
# 19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
array = np.arange(15,56)
print(array)
array = array[1:-1]
print("\nRemoving first and last element\n",array)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]

Removing first and last element
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [66]:
# 21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
array = np.arange(5,51,5).reshape(10)
print(array)

[ 5 10 15 20 25 30 35 40 45 50]


In [69]:
# 22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
array = np.arange(20)
print(array)
array[9:16] *= -1
print("\nChanging sign of numbers from 9 to 15\n",array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Changing sign of numbers from 9 to 15
 [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


In [79]:
# 24. Write a NumPy program to multiply the values of two given vectors.
array_1 = np.arange(10).reshape((5,2))
array_2 = np.arange(11,21).reshape((2,5))
print(array_1,"\n",array_2,"\n")
print(np.dot(array_1,array_2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 
 [[11 12 13 14 15]
 [16 17 18 19 20]] 

[[ 16  17  18  19  20]
 [ 70  75  80  85  90]
 [124 133 142 151 160]
 [178 191 204 217 230]
 [232 249 266 283 300]]


In [82]:
# 25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
array = np.linspace(10,21,3*4).reshape(3,4)
print(array)

[[10. 11. 12. 13.]
 [14. 15. 16. 17.]
 [18. 19. 20. 21.]]


In [86]:
# 26. Write a NumPy program to find the number of rows and columns of a given matrix.
array = np.linspace(10,21,3*4).reshape(3,4)
print(array.shape)

(3, 4)


In [95]:
# 28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
array = np.ones((10,10))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [107]:
# 29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
array = np.zeros((5,5))
array = np.diag(np.arange(1,6))
print(array)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [129]:
# 32. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.
array =  np.arange(1,26).reshape(5,5)
print(array)
print("\n sum of elements\n",array.sum())
print("\nsum of rows\n",array.sum(axis=1))
print("\nsum of column\n",array.sum(axis=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 sum of elements
 325

sum of rows
 [ 15  40  65  90 115]

sum of column
 [55 60 65 70 75]


In [137]:
# 53. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.
array = np.arange(25).reshape(5,5)
print(array,"\n")


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 



In [128]:
# 56. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.
array  = np.arange(3*4*5).reshape(3,4,5)
print(array)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [126]:
# 57. Write a NumPy program to create a 4x4 array, now create a new array from the said array swapping first and last, second and third columns.
array_1 = np.arange(4*4).reshape(4,4)
print(array_1)
array_2 = np.zeros((4,4))
array_2[:,0] = array_1[:,-1]
array_2[:,-1] = array_1[:,0]
array_2[:,1] = array_1[:,2]
array_2[:,2] = array_1[:,1]
print(array_2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3.  2.  1.  0.]
 [ 7.  6.  5.  4.]
 [11. 10.  9.  8.]
 [15. 14. 13. 12.]]
