In [2]:
import numpy as np

In [15]:
array = np.array([0,1,2,3,4,5,6,7,8,9])
print(array)

# print the type of array here array is object of class numpy.ndarray
print(type(array))

# print datatype of array
print(array.dtype)

# print size of each element in array here int8 so 8bit = 1byte
print(array.itemsize)

# print number of elements in array
print(array.size)

# create array with desired datatype
array_1 = np.array([2,4,6,8,10],dtype="int8")

print(array_1.dtype)
print(array_1.ndim)
print(array_1.itemsize)
print(array_1.size)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int32
4
10
int8
1
1
5


In [18]:
# indexing

array[2:8]

array([2, 3, 4, 5, 6, 7])

In [31]:
# two dimentional array 
twod_array = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
print(twod_array)
print(twod_array.dtype)

# print dimensition of array here twod_array is a 2D array
print(twod_array.ndim)

print(twod_array.itemsize)
print(twod_array.size)

# print the shape of array ie number of rows and column
print(twod_array.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
int32
2
4
12
(2, 6)


In [42]:
# create array using arange here array is created whith values in a given range
array_2 = np.arange(10,100,2)
print(array_2)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


In [28]:
# create array using linspace here array is created with values in a given range with given partition
array_3 = np.linspace(1,10,15)
print(array_3)
np.any(array_3)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]


True

In [29]:
# create array with specified datatype
array_4 = np.arange(1000000,dtype = "int32")
print(array_4)
print(array_4.itemsize)

[     0      1      2 ... 999997 999998 999999]
4


In [58]:
# create array with random function    
array_5 = np.random.random(10)
print(array_5)

[0.56479042 0.73693033 0.3645987  0.56968435 0.92939019 0.2538793
 0.9134351  0.18513169 0.96614508 0.92590471]


In [21]:
# reshape function
array_6 = np.arange(10*10).reshape(10,10)
print(array_6)
np.all(array_6)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


False

In [7]:
 np.zeros((10,10),"int32")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
 np.ones((10,10),"int32")

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [16]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [28]:
#slicing 2D array
array_7 = np.arange(25).reshape(5,5)
print(array_7)

# selecting a particular element
array_7[2,2]

# selecting a particular row and column
array_7[0:5,4]
array_7[:,4]
array_7[0:5,2:4]
array_7[:,-1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 4,  9, 14, 19, 24])

In [2]:
# slicing 3D array
array_8 = np.array([[[0,1,2],[3,4,5],[6,7,8]]])
print(array_8)
print(array_8.shape)
array_8[0,:,:]

array_8[:,2,:]
array_8[:,:,2]
array_8[0,1:3,1:3]
array_8[0,...]

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
(1, 3, 3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr = np.array([1,2,3,4])
print(arr)

# arr_2 is view of arr
arr_2 = arr[1:4]
print(arr_2)

# base used to show where array is derived
print(arr.base)
print(arr_2.base)

# copy is used to create copy of array
arr_3 = np.copy(arr)
print(arr_3)
print(arr_3.base)

# change in view cause the orignial array to change also copy does not have this problem
arr_2[1] = 1
print(arr_2)
print(arr)

[1 2 3 4]
[2 3 4]
None
[1 2 3 4]
[1 2 3 4]
None
[2 1 4]
[1 2 1 4]


In [31]:
# convert nd array to 1 dimentional array
arr = np.arange(4*4).reshape(4,4)
arr_2 = arr.ravel()
print(arr)
print(arr_2)
arr_3 = np.arange(2*3*2).reshape(2,3,2)
print(arr_3)
arr_4 = arr_3.ravel()
print(arr_4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [35]:
arr = np.eye(10)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [70]:
# stacks arrays verticaly ie rowwise
arr = np.array([1,2,3])
arr_2 = np.array([4,5,6])
print(np.vstack([arr,arr_2]))

arr_3 = np.array([[1],[2],[3]])
arr_4 = np.array([[4],[5],[6]])
np.vstack([arr_3,arr_4])

[[1 2 3]
 [4 5 6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [64]:
# stacks arrays horizontaly ie columnwise
arr = np.array([1,2,3])
arr_2 = np.array([4,5,6])
print(np.hstack([arr,arr_2]))

arr_3 = np.array([[1],[2],[3]])
arr_4 = np.array([[4],[5],[6]])
np.hstack([arr_3,arr_4])

[1 2 3 4 5 6]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [72]:
# stacks arrays horizontaly ie columnwise
arr = np.array([1,2,3])
arr_2 = np.array([4,5,6])
print(np.column_stack([arr,arr_2]))

arr_3 = np.array([[1],[2],[3]])
arr_4 = np.array([[4],[5],[6]])
np.column_stack([arr_3,arr_4])

[[1 4]
 [2 5]
 [3 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [73]:
# stacks arrays verticaly ie rowwise
arr = np.array([1,2,3])
arr_2 = np.array([4,5,6])
print(np.row_stack([arr,arr_2]))

arr_3 = np.array([[1],[2],[3]])
arr_4 = np.array([[4],[5],[6]])
np.row_stack([arr_3,arr_4])

[[1 2 3]
 [4 5 6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [3]:
arr = np.arange(5*5).reshape(5,5)
print(arr)
print("\n",arr.min(axis = 1),"\n")
print(arr.cumsum(axis = 0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

 [ 0  5 10 15 20] 

[[ 0  1  2  3  4]
 [ 5  7  9 11 13]
 [15 18 21 24 27]
 [30 34 38 42 46]
 [50 55 60 65 70]]


In [50]:
array_1 = np.array([1,2,3,4,5])
array_2 = np.array([6,7,8,9,10])
array_3 = np.arange(4).reshape(2,2)
print("Dot product",array_1.dot(array_2))
print("vector dot product",np.vdot(array_1,array_2))
print(array_3)
print(np.linalg.matrix_power(array_3,2))
print(np.linalg.matrix_rank(array_3))
print(np.trace(array_3))
print(np.linalg.eigh(array_3))

Dot product 130
vector dot product 130
[[0 1]
 [2 3]]
[[ 2  3]
 [ 6 11]]
2
3
(array([-1.,  4.]), array([[-0.89442719,  0.4472136 ],
       [ 0.4472136 ,  0.89442719]]))


In [51]:
from numpy.linalg import inv
inv(array_3)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [69]:
# Broadcasting
array_1 = np.arange(3*3*3).reshape(3,3,3)
print("array_1\n",array_1)
array_2 = np.array([1,2,3])
print("\narray_2\n",array_2)
print("\nsum\n",array_2+array_1)

array_1
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

array_2
 [1 2 3]

sum
 [[[ 1  3  5]
  [ 4  6  8]
  [ 7  9 11]]

 [[10 12 14]
  [13 15 17]
  [16 18 20]]

 [[19 21 23]
  [22 24 26]
  [25 27 29]]]
